apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ocsinventory.fullname" . }}
  labels:
    {{- include "ocsinventory.labels" . | nindent 4 }}
  {{- if .Values.deploymentAnnotations }}
  annotations:
    {{ toYaml .Values.deploymentAnnotations | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ocsinventory.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ocsinventory.labels" . | nindent 8 }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          - name: OCS_DB_NAME
            valueFrom:
              secretKeyRef:
                  name: {{ template "ocsinventory.fullname" . }}
                  key: db-name
          - name: OCS_DB_PASS
            valueFrom:
              secretKeyRef:
                  name: {{ template "ocsinventory.fullname" . }}
                  key: db-pass
          - name: OCS_DB_SERVER
            valueFrom:
              secretKeyRef:
                  name: {{ template "ocsinventory.fullname" . }}
                  key: db-host
          - name: OCS_DB_USER
            valueFrom:
              secretKeyRef:
                  name: {{ template "ocsinventory.fullname" . }}
                  key: db-user
          - name: OCS_SSL_ENABLED
            value: "0"
          - name: OCS_DBI_PRINT_ERROR
            value: "0"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/ocsinventory-server
              name: {{ template "ocsinventory.fullname" . }}-data
              subPath: perlcomdata
            - mountPath: /usr/share/ocsinventory-reports/ocsreports/extensions
              name: {{ template "ocsinventory.fullname" . }}-data
              subPath: ocsreportsdata
            - mountPath: /var/lib/ocsinventory-reports
              name: {{ template "ocsinventory.fullname" . }}-data
              subPath: varlibdata
            - mountPath: /etc/apache2/conf-available
              name: {{ template "ocsinventory.fullname" . }}-data
              subPath: httpdconfdata
            - mountPath: /etc/php/8.1/apache2/conf.d/ocsinventory.ini
              name: {{ template "ocsinventory.fullname" . }}-config
              subPath: phpconfig
        {{- if .Values.metrics.enabled }}
        - name: {{ .Chart.Name }}-apache-metrics
          image: "{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9117
              protocol: TCP
        {{- end }}
      volumes:
        - name: {{ template "ocsinventory.fullname" . }}-data
          persistentVolumeClaim:
            {{- if .Values.persistence.existingClaim }}
            claimName: {{ .Values.persistence.existingClaim }}
            {{- else }}
            claimName: {{ template "ocsinventory.fullname" . }}-data
            {{- end }}
        - name: {{ template "ocsinventory.fullname" . }}-config
          configMap:
            name: {{ template "ocsinventory.fullname" . }}-config
            defaultMode: 420
